"""LLM provider with content-addressed caching and hard budget enforcement.

Three requirements shape this module, all of them about keeping the science valid
rather than about convenience.

**Reproducibility.** Every response is cached on disk under a hash of
``(provider, model, prompt, generation parameters)``. A rerun with the same config
replays byte-identical responses and makes zero network calls, so the published
results can be regenerated by anyone -- including without an API key, via
``cache_only``. Without this, an LLM-in-the-loop experiment is not reproducible at all,
because the provider's weights can change under you between runs.

**Budget safety.** Free-tier Gemini allows on the order of 1,000 requests a day. An
experiment that silently exceeds its budget fails halfway through an overnight run and
wastes a day. :class:`LLMClient` therefore enforces a hard call ceiling and raises
before spending rather than after.

**Honest accounting.** Calls, cache hits, tokens and latency are all counted, because
H4 is a claim about cost and an unmeasured cost claim is not evidence.

Temperature defaults to 0. Sampling variability would otherwise be confounded with the
effect under study, and the seeds in this project are meant to vary the *policy*, not
the text generator.
"""

from __future__ import annotations

import hashlib
import json
import os
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from core.logging import get_logger
from core.paths import LLM_CACHE_DIR

log = get_logger("llm")

__all__ = ["LLMClient", "LLMResponse", "LLMBudgetExceeded", "CacheMiss"]


class LLMBudgetExceeded(RuntimeError):
    """Raised when a run would exceed its configured call ceiling."""


class CacheMiss(RuntimeError):
    """Raised in ``cache_only`` mode when a prompt has no cached response."""


#: Markers that identify a retryable provider failure. Matched case-insensitively
#: against the exception text because providers surface these very differently.
_TRANSIENT_MARKERS = (
    "429", "rate", "quota", "503", "unavailable", "deadline", "timeout", "500",
    "502", "504", "overloaded", "connection",
)

#: Markers that identify a *daily* cap specifically. A per-minute limit clears on its
#: own; a daily one does not, and the only useful response is a different key.
_DAILY_QUOTA_MARKERS = ("perday", "per day", "requests per day", "daily limit", "rpd")


def _is_transient(exc: Exception) -> bool:
    text = str(exc).lower()
    return any(marker in text for marker in _TRANSIENT_MARKERS)


def _is_daily_quota(text: str) -> bool:
    lowered = text.lower().replace("_", "")
    return any(marker in lowered for marker in _DAILY_QUOTA_MARKERS)


class _RateLimiter:
    """Token bucket over a sliding one-minute window.

    Provider free tiers are quoted per minute (15 requests/minute for Gemini
    Flash-Lite at the time of writing). Without a limiter, concurrent workers discover
    the limit only by being rejected, and the exponential backoff that follows wastes
    far more wall-clock than simply waiting for a slot: an over-subscribed pool spends
    most of its time sleeping off 429s and finishes slower than a single-threaded
    client would. Pacing requests to just under the documented limit is strictly
    faster, and it is also the polite thing to do to a shared service.
    """

    def __init__(self, per_minute: float) -> None:
        self.per_minute = float(per_minute)
        self._times: list[float] = []
        self._lock = threading.Lock()

    def acquire(self) -> None:
        if self.per_minute <= 0:
            return
        while True:
            with self._lock:
                now = time.monotonic()
                self._times = [t for t in self._times if now - t < 60.0]
                if len(self._times) < self.per_minute:
                    self._times.append(now)
                    return
                # Wait until the oldest request in the window falls out of it.
                wait = 60.0 - (now - self._times[0]) + 0.05
            time.sleep(max(wait, 0.01))


@dataclass
class LLMResponse:
    text: str
    model: str
    cached: bool = False
    prompt_tokens: int = 0
    completion_tokens: int = 0
    latency_s: float = 0.0
    error: str | None = None

    @property
    def total_tokens(self) -> int:
        return self.prompt_tokens + self.completion_tokens

    def json(self) -> dict[str, Any] | None:
        """Parse the response as JSON, tolerating markdown code fences.

        Models routinely wrap JSON in ```json fences despite instructions not to;
        treating that as a parse failure would discard usable responses and bias the
        LLM arms downward.
        """
        text = self.text.strip()
        if text.startswith("```"):
            lines = [ln for ln in text.splitlines() if not ln.strip().startswith("```")]
            text = "\n".join(lines).strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            # Last resort: the outermost brace-delimited span.
            start, end = text.find("{"), text.rfind("}")
            if 0 <= start < end:
                try:
                    return json.loads(text[start : end + 1])
                except json.JSONDecodeError:
                    return None
            return None


@dataclass
class LLMClient:
    """Cached, budgeted client. Provider-agnostic by design."""

    provider: str = "gemini"
    model: str = "gemini-3.5-flash-lite"
    temperature: float = 0.0
    max_output_tokens: int = 1024
    max_calls: int = 5000
    cache_only: bool = False
    cache_dir: Path = field(default_factory=lambda: LLM_CACHE_DIR)
    max_retries: int = 5
    #: Requests per minute. Defaults just under the Gemini free-tier limit of 15;
    #: raise it when the project has billing enabled. Set to 0 to disable pacing.
    requests_per_minute: float = 14.0
    #: Groq reasoning models ("gpt-oss-*") put their chain of thought in a separate
    #: field and bill it as completion tokens. Low effort keeps the answer intact while
    #: cutting reasoning roughly sixfold, which matters because Groq's binding free-tier
    #: constraint is tokens per minute. Ignored by providers that do not support it.
    reasoning_effort: str | None = None

    n_calls: int = field(default=0, init=False)
    n_cache_hits: int = field(default=0, init=False)
    n_errors: int = field(default=0, init=False)
    total_prompt_tokens: int = field(default=0, init=False)
    total_completion_tokens: int = field(default=0, init=False)
    total_latency_s: float = field(default=0.0, init=False)
    _client: Any = field(default=None, init=False, repr=False)
    # Guards the counters and the lazily-built provider client. Policies may issue
    # calls from a thread pool (the decision for one instance never depends on
    # another's), and unsynchronised ``+=`` on the accounting fields would silently
    # under-report cost -- which is a reported quantity here, not a diagnostic.
    _lock: Any = field(default_factory=threading.Lock, init=False, repr=False)
    _limiter: Any = field(default=None, init=False, repr=False)
    _keys: Any = field(default=None, init=False, repr=False)
    _key_index: int = field(default=0, init=False, repr=False)

    def __post_init__(self) -> None:
        self.cache_dir = Path(self.cache_dir)
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self._limiter = _RateLimiter(self.requests_per_minute)

    # -- cache -------------------------------------------------------------- #

    def _cache_key(self, prompt: str, system: str | None) -> str:
        fields = {
            "provider": self.provider,
            "model": self.model,
            "temperature": self.temperature,
            "max_output_tokens": self.max_output_tokens,
            "system": system or "",
            "prompt": prompt,
        }
        # Two runs of the same reasoning model at different effort levels are two
        # different experiments and must not share an entry. The field is added only
        # when set, so every response cached before reasoning models were introduced
        # keeps the key it was written under instead of being silently orphaned.
        if self.reasoning_effort:
            fields["reasoning_effort"] = self.reasoning_effort
        payload = json.dumps(fields, sort_keys=True)
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()

    def _cache_path(self, key: str) -> Path:
        # Shard by prefix: a flat directory with tens of thousands of entries is slow
        # to list on Windows.
        return self.cache_dir / key[:2] / f"{key}.json"

    def _read_cache(self, key: str) -> LLMResponse | None:
        path = self._cache_path(key)
        if not path.exists():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return None
        return LLMResponse(
            text=data["text"],
            model=data.get("model", self.model),
            cached=True,
            prompt_tokens=data.get("prompt_tokens", 0),
            completion_tokens=data.get("completion_tokens", 0),
        )

    def _write_cache(self, key: str, response: LLMResponse, prompt: str,
                     system: str | None) -> None:
        path = self._cache_path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(
                {
                    "text": response.text,
                    "model": response.model,
                    "prompt_tokens": response.prompt_tokens,
                    "completion_tokens": response.completion_tokens,
                    "latency_s": response.latency_s,
                    # Stored for auditability: a reviewer can inspect exactly what the
                    # agent was asked and what it replied.
                    "prompt": prompt,
                    "system": system,
                    # Recorded so an audit can tell which experiment an entry belongs
                    # to without recomputing its key.
                    "reasoning_effort": self.reasoning_effort,
                    "created": time.time(),
                },
                indent=2,
            ),
            encoding="utf-8",
        )

    # -- generation --------------------------------------------------------- #

    def generate(self, prompt: str, system: str | None = None) -> LLMResponse:
        """Return a completion, from cache when available."""
        key = self._cache_key(prompt, system)
        cached = self._read_cache(key)
        if cached is not None:
            with self._lock:
                self.n_cache_hits += 1
            return cached

        if self.cache_only:
            raise CacheMiss(
                f"cache_only is set but prompt {key[:12]} is not cached. Run once with "
                f"cache_only disabled to populate the cache, or check that the model "
                f"and temperature match the cached run."
            )
        with self._lock:
            if self.n_calls >= self.max_calls:
                raise LLMBudgetExceeded(
                    f"call ceiling of {self.max_calls} reached. Raise llm.max_calls "
                    f"deliberately rather than by accident."
                )
            # Reserve the slot before spending it, so concurrent callers cannot
            # collectively overshoot the ceiling.
            self.n_calls += 1

        response = self._call_provider(prompt, system)
        with self._lock:
            self.total_prompt_tokens += response.prompt_tokens
            self.total_completion_tokens += response.completion_tokens
            self.total_latency_s += response.latency_s
            if response.error:
                self.n_errors += 1
        if not response.error:
            self._write_cache(key, response, prompt, system)
        return response

    def _call_provider(self, prompt: str, system: str | None) -> LLMResponse:
        if self.provider == "gemini":
            return self._call_gemini(prompt, system)
        if self.provider == "groq":
            return self._call_groq(prompt, system)
        raise ValueError(f"unsupported provider {self.provider!r}")

    # -- key rotation ------------------------------------------------------- #

    def _api_keys(self) -> list[str]:
        """All configured keys for this provider, in preference order.

        Gemini's free-tier daily quota is enforced **per project**, not per key, so a
        second key minted in the same project buys nothing while a key from a different
        project doubles the budget. Reading a numbered series of environment variables
        lets a study be run across several projects without changing any code, which is
        the difference between finishing an experiment in a day and in three.
        """
        prefix = "GROQ_API_KEY" if self.provider == "groq" else "GEMINI_API_KEY"
        keys, seen = [], set()
        for name in [prefix] + [f"{prefix}_{i}" for i in range(2, 10)]:
            value = os.environ.get(name, "").strip()
            if value and value not in seen:
                seen.add(value)
                keys.append(value)
        return keys

    def _rotate_key(self, exhausted: str) -> bool:
        """Advance past a key whose daily quota is spent. True if another remains."""
        with self._lock:
            if self._keys is None:
                self._keys = self._api_keys()
            if self._keys and self._keys[self._key_index] != exhausted:
                return True  # another thread already rotated
            if self._key_index + 1 >= len(self._keys):
                return False
            self._key_index += 1
            self._client = None  # force a rebuild against the new key
            log.warning(
                "daily quota exhausted on key %d/%d; switching to the next one",
                self._key_index, len(self._keys),
            )
            return True

    def _current_key(self) -> str:
        with self._lock:
            if self._keys is None:
                self._keys = self._api_keys()
            if not self._keys:
                env = "GROQ_API_KEY" if self.provider == "groq" else "GEMINI_API_KEY"
                raise RuntimeError(
                    f"{env} is not set. Put it in a .env file (which is gitignored) "
                    f"or export it. Never commit it, and rotate any key that has been "
                    f"pasted into a chat or terminal log."
                )
            return self._keys[self._key_index]

    def _ensure_gemini(self):
        if self._client is not None:
            return self._client
        from google import genai

        key = self._current_key()
        with self._lock:
            if self._client is None:
                self._client = genai.Client(api_key=key)
        return self._client

    def _ensure_groq(self):
        """Groq speaks the OpenAI wire protocol, so the OpenAI SDK is the client.

        Plain ``urllib`` is not usable here: Groq sits behind Cloudflare, which rejects
        the default Python user agent with a 1010 before the request reaches the API.
        """
        if self._client is not None:
            return self._client
        from openai import OpenAI

        key = self._current_key()
        with self._lock:
            if self._client is None:
                self._client = OpenAI(
                    api_key=key, base_url="https://api.groq.com/openai/v1"
                )
        return self._client

    def _call_gemini(self, prompt: str, system: str | None) -> LLMResponse:
        from google.genai import types

        client = self._ensure_gemini()
        # Captured before the loop so the quota handler can tell whether the key it
        # failed on is still the current one; another thread may already have rotated.
        key = self._current_key()
        config = types.GenerateContentConfig(
            temperature=self.temperature,
            max_output_tokens=self.max_output_tokens,
            system_instruction=system,
        )

        delay = 2.0
        last_error = ""
        for attempt in range(self.max_retries):
            self._limiter.acquire()
            t0 = time.perf_counter()
            try:
                result = client.models.generate_content(
                    model=self.model, contents=prompt, config=config
                )
                latency = time.perf_counter() - t0
                usage = getattr(result, "usage_metadata", None)
                return LLMResponse(
                    text=(result.text or ""),
                    model=self.model,
                    prompt_tokens=getattr(usage, "prompt_token_count", 0) or 0,
                    completion_tokens=getattr(usage, "candidates_token_count", 0) or 0,
                    latency_s=latency,
                )
            except Exception as exc:  # noqa: BLE001 - provider errors are varied
                last_error = f"{type(exc).__name__}: {exc}"
                if self._handle_quota(exc, key):
                    client, key = self._ensure_gemini(), self._current_key()
                    continue
                if not _is_transient(exc) or attempt == self.max_retries - 1:
                    break
                # Free-tier limits are per-minute, so back off in seconds not ms.
                log.warning("LLM call failed (%s); retrying in %.0fs", last_error, delay)
                time.sleep(delay)
                delay = min(delay * 2, 60.0)

        log.error("LLM call failed permanently: %s", last_error)
        return LLMResponse(text="", model=self.model, error=last_error)

    def _call_groq(self, prompt: str, system: str | None) -> LLMResponse:
        """Groq via its OpenAI-compatible endpoint.

        Two provider-specific details matter. Groq's reasoning models emit their chain
        of thought in a separate ``reasoning`` field and the answer in ``content``, so a
        completion budget sized for the answer alone returns an empty string --- hence
        ``reasoning_effort='low'`` and a generous ``max_tokens``. And the binding free-tier
        constraint is tokens per minute, not requests per minute, so the caller paces on
        the token budget rather than the request count.
        """
        client = self._ensure_groq()
        key = self._current_key()
        messages = ([{"role": "system", "content": system}] if system else []) + [
            {"role": "user", "content": prompt}
        ]

        delay = 2.0
        last_error = ""
        for attempt in range(self.max_retries):
            self._limiter.acquire()
            t0 = time.perf_counter()
            try:
                kwargs: dict[str, Any] = {
                    "model": self.model,
                    "messages": messages,
                    "temperature": self.temperature,
                    "max_tokens": self.max_output_tokens,
                }
                if self.reasoning_effort:
                    kwargs["reasoning_effort"] = self.reasoning_effort
                result = client.chat.completions.create(**kwargs)
                latency = time.perf_counter() - t0
                usage = result.usage
                return LLMResponse(
                    text=(result.choices[0].message.content or ""),
                    model=self.model,
                    prompt_tokens=getattr(usage, "prompt_tokens", 0) or 0,
                    completion_tokens=getattr(usage, "completion_tokens", 0) or 0,
                    latency_s=latency,
                )
            except Exception as exc:  # noqa: BLE001 - provider errors are varied
                last_error = f"{type(exc).__name__}: {exc}"
                if self._handle_quota(exc, key):
                    client, key = self._ensure_groq(), self._current_key()
                    continue
                if not _is_transient(exc) or attempt == self.max_retries - 1:
                    break
                log.warning("LLM call failed (%s); retrying in %.0fs", last_error, delay)
                time.sleep(delay)
                delay = min(delay * 2, 60.0)

        log.error("LLM call failed permanently: %s", last_error)
        return LLMResponse(text="", model=self.model, error=last_error)

    def _handle_quota(self, exc: Exception, key: str) -> bool:
        """Rotate to the next key on a *daily* quota error. True if a retry should run.

        Distinguishing a daily cap from a per-minute one matters: backing off and
        retrying clears a per-minute limit but will never clear a daily one, so without
        this the client burns its remaining wall-clock on calls that cannot succeed.
        """
        text = str(exc)
        if not _is_daily_quota(text):
            return False
        return self._rotate_key(key)

    # -- accounting --------------------------------------------------------- #

    def stats(self) -> dict[str, float]:
        total = self.n_calls + self.n_cache_hits
        return {
            "llm_calls": float(self.n_calls),
            "llm_cache_hits": float(self.n_cache_hits),
            "llm_cache_hit_rate": float(self.n_cache_hits / total) if total else 0.0,
            "llm_errors": float(self.n_errors),
            "llm_prompt_tokens": float(self.total_prompt_tokens),
            "llm_completion_tokens": float(self.total_completion_tokens),
            "llm_total_tokens": float(
                self.total_prompt_tokens + self.total_completion_tokens
            ),
            "llm_latency_s": float(self.total_latency_s),
        }
